version: '3.9'

services:
  resp32flow:
    container_name: resp32flow
    build: ./
    volumes:
      - ./:/app:rw
      - /dev:/dev
    tty: true
    device_cgroup_rules:
      - 'c 188:* rwm'

  website:
    image: node:latest
    working_dir: "/app"
    container_name: website
    volumes:
      - ./website/:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: "npm start"