env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_" # Don't report if an arg starts with a _
ignorePatterns:
  - build/**

settings:
  react:
    version: detect
