version: "3.9"
volumes:
  node_modules:

services:
  website:
    image: node:latest
    working_dir: "/app"
    container_name: resp32flow-website
    volumes:
      - ./:/app:ro
      - ./package-lock.json:/app/package-lock.json:rw
      - node_modules:/app/node_modules:rw
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: "bash -c 'npm i && npm start'"

  json:
    container_name: jsonserver
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3005 -w db.json -r routes.json
    ports:
      - 3005:3005
    volumes:
      - ./test_db:/data:rw
