version: '3.9'
services:
  website:
    image: node:latest
    working_dir: "/app"
    container_name: website
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: "npm start"