version: '3.9'
services:
  website:
    image: node:latest
    working_dir: "/app"
    container_name: website
    volumes:
      - ../website:/app:ro
      - ../website/node_modules:/app/node_modules:rw
      - ../website/package-lock.json:/app/package-lock.json:rw
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: "bash -c 'npm i && npm start'"