version: "3"
volumes:
  node_modules:

services:
  website:
    build: .
    working_dir: /home/node/app
    container_name: resp32flow-website
    volumes:
      - node_modules:/home/node/app/node_modules
      - ./package-lock.json:/home/node/app/package-lock.json:rw
      - ./:/home/node/app
    ports:
      - 3000:3000
    # environment:
    # - NODE_ENV=production
    command: ["bash", "-c", "npm i --ignore-scripts && npm start"]
