version: '3.9'

services:
  website:
    container_name: website
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:ro
      - ./node_modules:/app/node_modules:rw
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    entrypoint: ['npm', 'start']